import React from 'react';
import { motion } from 'framer-motion';
import { SparklesIcon, CpuChipIcon } from '@heroicons/react/24/outline';

const AIInsightCard = ({ insight, title = "AI-Powered Insight", date }) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-gradient-to-br from-purple-600 to-blue-600 rounded-2xl shadow-lg p-4 sm:p-6 text-white"
    >
      <div className="flex items-start justify-between mb-4">
        <div className="flex items-center space-x-3">
          <div className="p-2 bg-white/20 rounded-lg">
            <SparklesIcon className="w-5 h-5 sm:w-6 sm:h-6" />
          </div>
          <div>
            <h3 className="text-sm sm:text-base font-medium text-purple-100">{title}</h3>
            {date && (
              <p className="text-xs text-purple-200">
                {new Date(date).toLocaleDateString()}
              </p>
            )}
          </div>
        </div>
        <div className="px-2 py-1 bg-white/20 rounded-full text-xs flex items-center space-x-1">
          <CpuChipIcon className="w-3 h-3" />
          <span>Cerebras AI</span>
        </div>
      </div>
      
      <p className="text-sm sm:text-base leading-relaxed">
        {insight}
      </p>
      
      <div className="mt-4 pt-4 border-t border-white/20">
        <p className="text-xs text-purple-200">
          🤖 This insight is generated by AI and is for awareness only, not diagnostic.
        </p>
      </div>
    </motion.div>
  );
};

export default AIInsightCard;